### ISSUE TITLE
Find better name for package

### ISSUE THREAD

**Issue by Sebobo** [Sebobo/Shel.NodeTypes.Analyzer#2]
It's more about analysing and exploring the CR

**Comment by baschny** [comment]
Depends on the planned scope of the package. Currently for me it has less to do with the content repository itself (we cannot "explore" or analyse the CR itself - i.e. its data), but the NodeTypes. So in the current state I would expect it to be called `NodeTypes.Explorer` or `NodeTypes.Analyser` or something like that.

**Comment by Sebobo** [comment]
Thanks for the input!

Yes it's only partly accessing the Content Repository, but I will further extend not that -> the actual usage of defined node types. This was one of my primary use cases for this package.

To make it possible in a grown project to get rid of whole dependant structures of unused node types.
And then I want to help find nodes at some point instead of just counting them. So when you know you have 1 instance of old nodetype x, it would help you finding and replacing/removing it.

**Comment by Sebobo** [comment]
Renamed to `NodeTypes.Analyzer` :)
